version: '3.7'
services:
  web:
    build: .
    volumes:
      - .:/mnt/extra-addons
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8069:8069"
    command: odoo -d demo -i crm_apply
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  backend:
    build: backend
    depends_on:
      - web
    command: python3 receive.py
    tty: true
    restart: on-failure
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"